### ISSUE TITLE
Conveyor loses items

### ISSUE THREAD

**Issue by Vatisco** [YeetLand-1/mindustryinminecraft#1]
If a conveyor line is constantly supplied by a hopper (and then leads into another hopper then a chest), it loses items (looks like 1 every 6 items from my testing)

**Comment by YeetLand-1** [comment]
In my testing I lost ~20%

**Comment by Vatisco** [comment]
I've just confimed it

Even if a conveyor belt is clogged up, the hopper will still put items into the conveyor belt even though the belt can't fit it
which causes the items to disappear instead.

I'll see if i can find a way to fix this, this won't be an issue if we use a modded block to insert items however (Maybe a drill in the future)

**Comment by Vatisco** [comment]
Fixed.

Conveyors now output a Redstone signal which stops the hopper from voiding the items (also stops input into hoppers though. Just means I need to make it so the conveyors can input straight into chests properly)
